name: llm_vaz_cpu
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch=2.0.1
  - torchvision
  - torchaudio
  - cpuonly 
  - transformers=4.35.2
  - peft=0.7.1
  - accelerate=0.25.0
  - datasets=2.15.0
  - numpy
  - pyreadline3
  - pip:
    - huggingface-hub